export const launchLatestRes = {
  id: '109',
  upcoming: false,
  launch_success: true,
  details: null,
  is_tentative: false,
  launch_date_local: '2020-10-24T11:31:00-04:00',
  launch_year: '2020',
  links: {
    article_link: null,
    flickr_images: [],
    mission_patch: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
    mission_patch_small: 'https://images2.imgbox.com/9a/96/nLppz9HW_o.png',
    presskit: null,
    reddit_campaign:
      'https://www.reddit.com/r/spacex/comments/i63bst/starlink_general_discussion_and_deployment_thread/',
    reddit_launch:
      'https://www.reddit.com/r/spacex/comments/jhu37i/starlink_general_discussion_and_deployment_thread/',
    reddit_media: null,
    reddit_recovery: null,
    video_link: 'https://youtu.be/J442-ti-Dhg',
    wikipedia: 'https://en.wikipedia.org/wiki/Starlink',
  },
  rocket: {
    rocket: {
      name: 'Falcon 9',
      active: true,
      boosters: 0,
      company: 'SpaceX',
      cost_per_launch: 50000000,
      country: 'United States',
      stages: 2,
      type: 'rocket',
      description:
        'Falcon 9 is a two-stage rocket designed and manufactured by SpaceX for the reliable and safe transport of satellites and the Dragon spacecraft into orbit.',
    },
  },
  mission_name: 'Starlink-15 (v1.0)',
  static_fire_date_utc: '2020-11-21T16:31:00.000Z',
  tentative_max_precision: 'hour',
  launch_site: {
    site_id: 'ccafs_slc_40',
    site_name: 'CCAFS SLC 40',
    site_name_long: 'Cape Canaveral Air Force Station Space Launch Complex 40',
  },
  ships: [
    {
      id: 'GOMSTREE',
      model: null,
      name: 'GO Ms Tree',
      type: 'High Speed Craft',
      class: 15252765,
      year_built: 2015,
    },
    {
      id: 'GOMSCHIEF',
      model: null,
      name: 'GO Ms Chief',
      type: 'High Speed Craft',
      class: 14245747,
      year_built: 2014,
    },
    {
      id: 'JRTI-2',
      model: 'Marmac 303',
      name: 'Just Read The Instructions 2',
      type: 'Barge',
      class: null,
      year_built: 2015,
    },
    {
      id: 'GOQUEST',
      model: null,
      name: 'GO Quest',
      type: 'Cargo',
      class: null,
      year_built: 2014,
    },
  ],
}
